<?xml version="1.0"?>

<robot name="meine_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for the robot -->

  <!-- CHASSI-->

  <xacro:property name="width" value="0.1"/>
  <xacro:property name="length" value="0.2"/>
  <xacro:property name="height" value="0.0002"/>
  <xacro:property name="chassi_mass" value="5"/>

  <!-- MOTOR -->
  <xacro:property name="motor_width" value="0.02"/>
  <xacro:property name="motor_length" value="0.06"/>
  <xacro:property name="motor_height" value="0.02"/>

  <xacro:property name="x_pos" value="-0.03"/>
  <xacro:property name="y_pos" value="${width/2 - motor_width/2}"/>
  <xacro:property name="z_pos" value="${-motor_height/2}"/>

  <!-- BATTERY AND PI -->
  <xacro:property name="battery_width" value="0.065"/>
  <xacro:property name="battery_length" value="0.11"/>
  <xacro:property name="battery_height" value="0.05"/>
  <xacro:property name="battery_mass" value="5"/>

  <!-- CAMERA -->
  <xacro:property name="camera_width" value="0.03"/>
  <xacro:property name="camera_length" value="0.03"/>
  <xacro:property name="camera_height" value="0.02"/>

  <!-- HOKUYO -->
  <xacro:property name="hokuyo_width" value="0.1"/>

  <!-- CASTER-->
  <xacro:property name="radius_caster" value="0.01725"/>

  <!-- WHEEL-->

  <xacro:property name="radius_wheel" value="0.03"/>
  <xacro:property name="length_wheel" value="0.025"/>
  <xacro:property name="wheel_mass" value="5"/>

  <!-- INERTIA-->
  <xacro:property name='inertial' value="0.1"/>

</robot>
