map_type: costmap

obstacle_range: 2.1
raytrace_range: 3.0

transform_tolerance: 0.2

inflation_radius: .3
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor
update_frequency: 5.0
publish_frequency: 2.0

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /meine_bot/laser/scan, marking: true, clearing: true}
