local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   width: 4.0
   height: 4.0
   resolution: 0.02
   static_map: false
   transform_tolerance: 0.5
   planner_frequency: 1.0
   planner_patiente: 5.0
   rolling_window: true
